---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  modules_path: site
  manifests_path: manifests
  manifest: site.pp
  hiera_data_path: hieradata
  hiera_data_remote_path: /etc/puppet/hieradata
  ignore_spec_fixtures: true
  puppet_environment: vagrant
  custom_facts:
    tic_db_host: <%= ENV['TIC_DB_HOST'] %>
    packagecloud_master_token: <%= ENV['PACKAGECLOUD_MASTER_TOKEN'] %>
    master_password: <%= ENV['MASTER_PASSWORD'] %>
    ec2_instance_id: i-foo
    ec2_userdata: {}

transport:
  name: sftp

platforms:
  - name: centos-7.2

suites:
  - name: role-services
    provisioner:
      custom_facts:
        puppet_role: services
  - name: role-frontend
    provisioner:
      custom_facts:
        puppet_role: frontend
  - name: role-dataprep_dataset
    provisioner:
      custom_facts:
        puppet_role: dataprep_dataset
  - name: role-activemq
    provisioner:
      custom_facts:
        puppet_role: activemq
  - name: role-elasticsearch
    provisioner:
      custom_facts:
        puppet_role: elasticsearch
  - name: role-nexus
    provisioner:
      custom_facts:
        puppet_role: nexus
  - name: role-syncope
    provisioner:
      custom_facts:
        puppet_role: syncope
  - name: role-web
    provisioner:
      custom_facts:
        puppet_role: web
  - name: role-zookeeper
    provisioner:
      custom_facts:
        puppet_role: zookeeper
  - name: profile-base
    provisioner:
      manifests_path: test/integration
      manifest: profile-base/init.pp
      custom_facts:
        puppet_role: base
  - name: profile-elasticsearch
    provisioner:
      manifests_path: test/integration
      manifest: profile-elasticsearch/init.pp
      custom_facts:
        puppet_role: elasticsearch
  - name: profile-nexus
    provisioner:
      manifests_path: test/integration
      manifest: profile-nexus/init.pp
      custom_facts:
        puppet_role: nexus
  - name: profile-mongodb
    provisioner:
      manifests_path: test/integration
      manifest: profile-mongodb/init.pp
      custom_facts:
        puppet_role: mongodb
  - name: profile-activemq
    provisioner:
      manifests_path: test/integration
      manifest: profile-activemq/init.pp
      custom_facts:
        puppet_role: activemq
  - name: profile-zookeeper
    provisioner:
      manifests_path: test/integration
      manifest: profile-zookeeper/init.pp
      custom_facts:
        puppet_role: zookeeper
  - name: profile-syncope
    provisioner:
      manifests_path: test/integration
      manifest: profile-syncope/init.pp
      custom_facts:
        puppet_role: syncope
